#!/bin/bash

pushd .
rm -f cscope.files cscope.out
find -L . -iname '*.c' ! -iname '*.mod.c' \
	-o -iname '*.cpp' \
	-o -iname '*.h' \
	-o -iname '*.s' | grep -v "^\./tools/" > cscope.files
cscope -bki cscope.files
popd
